# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2108a6d2676d53e743ee255791b49728ee5553f120085b1f132d1c79f46eecfd533eba67ac7771aa531804198834260441070075dee7b0b782b7030a306074f3

test:
  secret_key_base: 6c36cbc3883edc748c51e8bda05582b742c3f8472322d67a17803b01a909cc20ccb38a9414e53c288357160e493cab540e6a8cb73b962c48887412c7932bafe3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
